### ISSUE TITLE
Deprecation warning with latest fastify

### ISSUE THREAD

**Issue by tswaters** [ToonvanStrijp/fastify-oauth-server#4]
The following is logged to the console when starting up the application.

> (node:3205905) [FSTDEP006] FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead. Property: oauth

It looks like it's setting some static methods on the request object, so maybe this can be ignored ( it is expected that all functions should use the same reference, across all requests )....   This should work to bypass the warning:

```js
fastify.decorateRequest('oauth', null)
fastify.addHook('onRequest', (req) => {
  req.oauth = {
    authenticate: authenticate,
    authorize: authorize,
    token: token
  }
})
```

**Comment by ToonvanStrijp** [comment]
@tswaters I'm not working on this package anymore, but feel free to create a pull request ;) then I'll create a new release.

**Comment by tswaters** [comment]
Sure, I've created the PR, #5

**Comment by tswaters** [comment]
Looks like the tests for this package are _very_ unhappy.  Sorry, no time to fix it.
